Repository VarquLabs/DolarBlueApp, pull requests merged in 2024-05, with the labels that each got.

#1 REFACTOR - [NO-TASK] - Reformat some lines in Calculator Screen
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
Labels: ready for review

#2 Feature_notetask
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
Labels: ready for review

#3 TEST -- NO_TASK -- first pr
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: ready for review

#4 TASK--NO-TASK-My first commit
  .gitignore
Labels: ready for review

#5 REFORMAT - [NO-TASK] - Single Line DTOs
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/DolarBlueDtos.kt
Labels: ready for review, refactor

#7 REFORMAT - 002 - Model separation
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/DolarBlueDtos.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/DolarBlueService.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/dto/BlueValueDto.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/dto/DolarBlueDto.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/repository/DolarBlueRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/model/BlueValue.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/model/DolarBlue.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/repository/DolarBlueRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/usecases/GetDolarBlueUseCase.kt
Labels: ready for review, refactor

#8 REFACTOR - 001 - Separate calculator modules
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/CalculatorModule.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/RepositoryModule.kt
Labels: ready for review, refactor

#9 REFACTOR - 003 - Rename "dolar" to "dollar" convention
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/DolarBlueService.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/DollarBlueService.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/dto/DollarBlueDto.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/repository/DolarBlueRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/repository/DollarBlueRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/CalculatorModule.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/model/DollarBlue.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/repository/DolarBlueRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/repository/DollarBlueRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/usecases/GetDollarBlueUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorState.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorViewModel.kt
Labels: ready for review, refactor

#10 FEATURE - 005 - Okhttp library and gsonConverterFactory
  app/build.gradle.kts
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/dto/BlueValueDto.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/remote/dto/DollarBlueDto.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/CalculatorModule.kt
  gradle/libs.versions.toml
Labels: ready for review, refactor, feature
