Repository VarquLabs/DolarBlueApp, pull requests merged in 2024-07, with the labels that each got.

#41 REFACTOR - HISTORY - Search conversions by money
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionsHistoryDao.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/QueryAndCurrency.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/ConversionsHistoryRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/SearchConversionsHistoryUseCase.kt
Labels: ready for review, refactor

#42 FEATURE - HISTORY - Delete conversion
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionsHistoryDao.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/ConversionsHistoryRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/DeleteConversionUseCase.kt
Labels: ready for review, refactor, feature

#43 FEATURE-DESIGNSYSTEM-Create theme for app
  app/src/main/java/com/varqulabs/dolarblue/MainActivity.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Color.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Theme.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Type.kt
  app/src/main/java/com/varqulabs/dolarblue/ui/theme/Color.kt
  app/src/main/java/com/varqulabs/dolarblue/ui/theme/Theme.kt
Labels: ready for review, priority, feature, r to merge

#46 FEATURE - SETTINGS - Screen Ui & Components
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/extensions/BooleanExtensions.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsState.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsUiEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/FavoriteCurrencyConfigs.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/MyAccountActions.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/NewsSettings.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/ThemeConfigs.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/aux/OptionTogglelable.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/aux/SelectableCurrency.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/aux/SingleCurrencySelector.kt
  app/src/main/res/values/strings.xml
Labels: ready for review, feature

#49 Rename Folder
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/FavoriteCurrencyConfigs.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/NewsSettings.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/ThemeConfigs.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/childrens/OptionTogglelable.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/childrens/SelectableCurrency.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/childrens/SingleCurrencySelector.kt
Labels: priority, hot-fix

#48 FEATURE- LOGIN- IMPLEMENTATION OF LOGIN LOGIC
  app/src/main/java/com/varqulabs/dolarblue/auth/domain/UserValidator.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/navigation/AuthRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginState.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginUiEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/components/DialogConfirmEmail.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/components/LoginForm.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Icons.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/components/DolarBlueActionButton.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/components/DolarBluePasswordTextField.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/components/DolarBlueTextField.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/ui/UiText.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/Routes.kt
  app/src/main/res/drawable/logo_app.webp
  app/src/main/res/values/strings.xml
Labels: ready for review, priority, feature

#50 FEATURE - HISTORY - INSERT CONVERSION AND OTHERS
  app/build.gradle.kts
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/buttons/Button5.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/utils/date/DateHelper.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/utils/keyboard/KeyboardHelper.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/utils/modifier/ModifierExtensions.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/ConversionsHistory.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/ConversionsHistoryRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/InsertConversionUseCase.kt
  app/src/main/res/drawable/eliminar.xml
  gradle/libs.versions.toml
Labels: ready for review, refactor, feature

#51 FEATURE - Get Notifications & News by Preferences Use Cases
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/preferences/PreferenceKey.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetArgentinianNewsEnabledByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetBolivianNewsEnabledByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDefaultThemeByPreferencesUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDollarNewsEnabledByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetNotificationsEnabledByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateArgentinianNewsEnabledFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateBolivianNewsEnabledFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateDollarNewsEnabledFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateNotificationsEnabledFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/NewsSettings.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/ThemeConfigs.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/childrens/OptionTogglelable.kt
Labels: ready for review, feature

#54 FEATURE - AUTH - Login with google account
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/varqulabs/dolarblue/auth/data/useCases/SignInWithGoogleAccountUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/di/AuthModule.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/components/LoginForm.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/repository/AuthRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ready for review, feature

#53 FEATURE - APP - Provide Dark Theme in App
  app/src/main/java/com/varqulabs/dolarblue/MainActivity.kt
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/preferences/PreferenceKey.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDefaultThemeByPreferencesUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDefaultThemeEnabledByPreferencesUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateDefaultThemeEnabledFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Theme.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsState.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/components/NewsSettings.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashState.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashViewModel.kt
Labels: ready for review, feature

#52 FEATURE - HISTORY - VIEWMODEL EVENTS
  app/src/main/java/com/varqulabs/dolarblue/core/domain/enums/CurrencyTab.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/CurrentExchangeRate.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryState.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryViewModel.kt
Labels: ready for review, feature

#55 FEATURE - CUSTOM DIALOG
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/components/dialog/DollarBlueDialog.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/buttons/Button5.kt
  app/src/main/res/values/strings.xml
Labels: ready for review, feature

#56 FIX - NO-TASK - When Remaining Branch
  app/src/main/java/com/varqulabs/dolarblue/history/navigation/HistoryRoute.kt
Labels: ready for review

#57 REFACTOR - Some Files & Apply Favorite Currency Use Case
  app/src/main/java/com/varqulabs/dolarblue/auth/navigation/AuthRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginUiEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/enums/Currency.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetFavoriteCurrencyByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetNotificationsEnabledByPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateFavoriteCurrencyFromPreferences.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/loadings/CircularLoading.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/top_bars/SimpleAppBar.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/utils/NavigateBetweenScreens.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsViewModel.kt
Labels: ready for review

#61 FIX - NO-TASK - Duplicate Google Services Library
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: ready for review, priority

#58 FEATURE - Provide Current User & Logout From Firebase
  app/src/main/java/com/varqulabs/dolarblue/MainActivity.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/data/useCases/LogoutUserUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/di/AuthModule.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/presentation/login/LoginViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetCurrentUser.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UpdateCurrentUser.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/desingsystem/Theme.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/model/User.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/repository/AuthRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsUiEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/presentation/SettingsViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashState.kt
  app/src/main/java/com/varqulabs/dolarblue/splash/SplashViewModel.kt
Labels: ready for review
