Repository VarquLabs/DolarBlueApp, pull requests merged in 2024-06, with the labels that each got.

#15 Sample file
  app/src/main/java/com/varqulabs/dolarblue/history/demo.kt
Labels: ready for review, feature

#20 BASE-FEATURE-AUTH
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/varqulabs/dolarblue/auth/data/useCases/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/services/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/UseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/useCases/UseCases.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/di/UserAuthModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/model/Models.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/model/User.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/repository/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/services/Services.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: no merge, ready for review, priority, feature

#21 HISTORY-BASE-FEATURE
  app/build.gradle.kts
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionDao.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/CurrentExchangeRateDao.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/entities/ConversionEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/entities/CurrentExchangeRateEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/CurrentExchangeRateRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/Conversion.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/ConversionRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/CurrentExchangeRateRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/usecases/UseCase.kt
  gradle/libs.versions.toml
Labels: ready for review, priority, feature

#22 FEATURE - MULTI-TASK - Data Store Initial Setup & Dark Mode Use Case
  app/build.gradle.kts
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorState.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/preferences/PreferenceKey.kt
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/preferences/repository/PreferencesRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/preferences/repository/PreferencesRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDefaultThemeByPreferences.kt
  gradle/libs.versions.toml
Labels: ready for review, feature

#24 FEATURE - AUTHENTICATION LOGIN LOGIC
  app/src/main/java/com/varqulabs/dolarblue/auth/data/useCases/LoginWithEmailAndPasswordUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/data/useCases/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/auth/domain/model/LoginRequest.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/data/repository/Repository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/di/UserAuthModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/repository/AuthRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/core/user/domain/repository/Repository.kt
Labels: no merge, ready for review, priority, feature

#29 FIX - Refactor Use Cases Folder & Remove Get Default Theme from Calculator VM
  app/src/main/java/com/varqulabs/dolarblue/calculator/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/domain/useCases/GetDollarBlueUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/core/di/PreferencesModule.kt
  app/src/main/java/com/varqulabs/dolarblue/core/domain/useCases/GetDefaultThemeByPreferencesUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/history/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/GetConversionsHistoryFlowUseCase.kt
Labels: ready for review, priority, hot-fix

#31 FEATURE - ADD DEPENDECIES
  app/build.gradle.kts
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/entities/ConversionEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/entities/CurrentExchangeRateEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/database/DBDollarBlueApp.kt
  app/src/main/java/com/varqulabs/dolarblue/core/data/local/database/converters/DBTypeConverter.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/Conversion.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/CurrentExchangeRate.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: ready for review, feature

#32 FEATURE - HISTORY AND CALCULATOR MAPPERS
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/entities/ConversionEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/entities/CurrentExchangeRateEntity.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/mappers/ConversionsMapper.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/data/local/database/mappers/CurrentExchangeRateMapper.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/entities/relations/ConversionsHistoryRelation.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/mappers/ConversionsHistoryMapper.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/model/Conversion.kt
Labels: ready for review, feature

#25 FEATURE - SETTINGS - Common Composables & Refactor Constants
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/loadings/CircularLoading.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/generics/top_bars/DrawerAppBar.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/model/DrawerItem.kt
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/utils/mvi/MVIContract.kt
  app/src/main/java/com/varqulabs/dolarblue/history/navigation/HistoryRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/Routes.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
  app/src/main/res/values/strings.xml
Labels: ready for review, priority, feature

#26 REFACTOR - NO-TASK - Calculator Module
  app/src/main/java/com/varqulabs/dolarblue/calculator/navigation/CalculatorRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorState.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorUiEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/calculator/presentation/CalculatorViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
  app/src/main/java/com/varqulabs/dolarblue/settings/navigation/SettingsRoute.kt
Labels: no merge, refactor

#27 REFACTOR - NO-TASK - History Module
  app/src/main/java/com/varqulabs/dolarblue/core/presentation/views/SimpleScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/history/navigation/HistoryRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/ConversionHistoryScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryEffect.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryEvent.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryState.kt
  app/src/main/java/com/varqulabs/dolarblue/history/presentation/HistoryViewModel.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
Labels: refactor

#28 FEATURE - NO-TASK - Add Navigation Drawer in App
  app/src/main/java/com/varqulabs/dolarblue/home/navigation/HomeRoute.kt
  app/src/main/java/com/varqulabs/dolarblue/home/presentation/HomeScreen.kt
  app/src/main/java/com/varqulabs/dolarblue/home/presentation/components/DrawerContent.kt
  app/src/main/java/com/varqulabs/dolarblue/navigation/NavGraph.kt
Labels: no merge, feature

#34 NO-TASK - Remove trailing commas from HomeScreen
  app/src/main/java/com/varqulabs/dolarblue/home/presentation/HomeScreen.kt
Labels: ready for review, refactor

#37 FEATURE - Typography and fonts added
  app/src/main/java/com/varqulabs/dolarblue/ui/theme/Type.kt
  app/src/main/res/font/bernard_mt_condensed.ttf
  app/src/main/res/font/nunito/nunito_black.ttf
  app/src/main/res/font/nunito/nunito_bold.ttf
  app/src/main/res/font/nunito/nunito_extrabold.ttf
  app/src/main/res/font/nunito/nunito_light.ttf
  app/src/main/res/font/nunito/nunito_regular.ttf
  app/src/main/res/font/nunito_black.ttf
  app/src/main/res/font/nunito_bold.ttf
  app/src/main/res/font/nunito_extrabold.ttf
  app/src/main/res/font/nunito_light.ttf
  app/src/main/res/font/nunito_regular.ttf
Labels: priority, feature

#38 FEATURE - HISTORY - Add & Get conversions favorites
  app/src/main/java/com/varqulabs/dolarblue/history/data/local/database/dao/ConversionsHistoryDao.kt
  app/src/main/java/com/varqulabs/dolarblue/history/data/repository/ConversionsHistoryRepositoryImpl.kt
  app/src/main/java/com/varqulabs/dolarblue/history/di/RepositoryModule.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/mappers/ConversionMapper.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/repository/ConversionsHistoryRepository.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/GetFavoriteConversionsHistoryUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/history/domain/useCases/UpdateConversionUseCase.kt
  app/src/main/java/com/varqulabs/dolarblue/ui/theme/Type.kt
Labels: ready for review, feature
